### ISSUE TITLE
seeds are much too plentiful from grass, more suggestions 

### ISSUE THREAD

**Issue by MentalMouse** [MinecraftModDevelopmentMods/HempFarmer#34]
Both getting and upgrading the seeds is way to generous, given that in Minecraft it's so easy to build up to huge fields of crops.  Playing with Crafttweaker suggests you're limited to integer weights for the grass drops, but other mods make it clear you have more control available for the crop drops.so I suggest the following, with config settings allowing for adjustments (but I'm seeing issues with the config too, see separate entry):

Breaking grass offers weight 1 for a single hemp seed.  A hemp crop has a 5% chance of dropping a sativa seed.  A sativa crop averages 1 hemp seed, and has 10% chance of dropping an indica seed, while an indica crop averages 1 hemp seed and 1 sativa seed.  All these are in addition to their own seeds.  

This will let a player occasionally turn up a hemp seed, and if they cultivate that, they will eventually get a sativa seed, and then in turn indica.  Given a seed of any type, they can easily multiply it into larger quantities.   The same-type seed drops might also be biased such that hemp offers the most seeds, while sativa and indica offer progressively less.

**Comment by MentalMouse** [comment]
Addendum: The grass drops are _especially_ over-generous since you're apparently generating hemp (etc.) _plants_ in at least one common biome!  I've seen them in savanna so far -- I only noticed now, because I added the mod to an existing world.

**Comment by SeqSEE** [comment]
This will be removed in the next release. See Dev builds
